client_config_backend: settings
client_config:
  client_id: 497902919791-uj1e7c31631suvq2kl9nng2b64bbtjum.apps.googleusercontent.com
  client_secret: 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 
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file